name: SelfHosted

on:
  pull_request:
    types:
      - labeled
    paths:
      - "Formula/**"

env:
  HOMEBREW_DEVELOPER: 1
  HOMEBREW_GITHUB_ACTIONS: 1
  HOMEBREW_NO_AUTO_UPDATE: 1
  GITHUB_ACTIONS_HOMEBREW_SELF_HOSTED: 1
jobs:
  get-runner-name-from-label:
    runs-on: ubuntu-latest
    if: github.repository == 'Homebrew/linuxbrew-core' && contains(github.event.pull_request.labels.*.name, 'self-hosted-ci')
    outputs:
      runner: ${{steps.runner-from-label.outputs.result}}
    steps:
      - name: Get self hosted runner name from label
        id: runner-from-label
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: { labels: labels } } = await github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            })
            const regex = /linux-self-hosted-([0-9]+)/;
            var runner = labels.filter(item => item.name.match(regex))[0].name;
            console.log('Found self-hosted runner: ' + runner);
            return runner;
      - name: Store runner name in file
        if: always()
        run: echo ${{fromJson(needs.get-runner-name-from-label.outputs.runner)}} > runner.txt
      - name: Upload runner name for stop-vm workflow
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: runner
          path: runner.txt
  tests-self-hosted:
    needs: [get-runner-name-from-label]
    strategy:
      matrix:
        os: [[self-hosted, '${{fromJson(needs.get-runner-name-from-label.outputs.runner)}}']]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 4320
    container:
      image: homebrew/ubuntu16.04:master
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - run: brew test-bot --only-cleanup-before

      - run: rm steps_output.txt

      - run: brew test-bot --only-setup

      - name: Run brew test-bot --only-formulae
        run: |
          mkdir ~/bottles
          cd ~/bottles
          brew test-bot --only-formulae --keep-old

      - name: Upload logs
        if: failure()
        uses: actions/upload-artifact@main
        with:
          name: logs (Linux)
          path: ~/bottles/logs

      - name: Delete logs and home
        if: always()
        run: |
          rm -rvf ~/bottles/logs
          rm -rvf ~/bottles/home

      - name: Count bottles
        id: bottles
        if: always()
        run: |
          cd ~/bottles
          count=$(ls *.json | wc -l | xargs echo -n)
          echo "$count bottles"
          echo "::set-output name=count::$count"

      - name: Upload bottles
        if: always() && steps.bottles.outputs.count > 0
        uses: actions/upload-artifact@main
        with:
          name: bottles
          path: ~/bottles

      - run: brew test-bot --only-cleanup-after
        if: always()

      - name: Post Cleanup
        if: always()
        run: rm -rvf ~/bottles
